### ISSUE TITLE
Can't provide 2 or more video

### ISSUE THREAD

**Issue by zepro75** [justinhunt/moodle-filter_videoeasy#1]
Hello,
In version 1.1.1, I can place 2 videos or more in the same bloc and I see 2 player, one for each video. With version 1.1.2, I see only the first player and the second one is not displayed. If I have links after the first video, the links are not visible.
Thank's.

**Comment by MartinaSnajder** [comment]
I have the same problem! No matter what template I use I only see the first video or sound. If I add another I can't see it or any content after it.

**Comment by justinhunt** [comment]
Indeed. I can confirm this issue. Its the new regular expression I put in to to parse params to the video url. I will fix it asap

**Comment by justinhunt** [comment]
I think this is fixed now. Please try it and let me know. I won't put on Moodle.org till its confirmed to be fixed

**Comment by zepro75** [comment]
Thank's Justin, it's OK for me. I see all video or links. Good job !
You can put it on moodle.org.

**Comment by MartinaSnajder** [comment]
Works great! Thank you for fast fix! Great plugin!

**Comment by justinhunt** [comment]
OK, thanks for the reports and testing. I will post it to Moodle.org from now.
