### ISSUE TITLE
Template not loading

### ISSUE THREAD

**Issue by stevefister** [justinhunt/moodle-filter_videoeasy#5]
Hello,

Thanks for the plugin! I'm wondering, does this work with Moodle 3.4.2? It does not seem to be loading the templates for Video JS (all other media plugins are disabled). I'm trying to add a poster image, but it doesn't seem to be working. In fact, it seems to be only using the built-in Video JS code from Moodle core and not the VideoEasy plugin...

**Comment by justinhunt** [comment]
Hi Steve, It should be working. Can you check:
i) you enabled the VideoEasy filter in the Moodle site admin, manage filters page.
ii) Have VideoEasy higher than MultiMedia plugins on the same page
iii) Have set a template to handle video extension you are using,

**Comment by stevefister** [comment]
Justin,

I figured out that it doesn’t work with the URL activity. Works fine in the
WYSIWYG editor of the activities.

Thank you.

**Comment by justinhunt** [comment]
Ah interesting. I should look at that thanks.
