### ISSUE TITLE
Incompatibility with OneTrust cookie manager

### ISSUE THREAD

**Issue by moodleacademy** [justinhunt/moodle-filter_videoeasy#8]
We use VideoEasy filter for playing embedded YouTube videos.
However, it seems that when we enable the [OneTrust cookie manager](https://www.onetrust.com/products/cookie-consent/) and if a user rejects all cookies then Youtube videos also cannot be displayed/played.

Using the default Youtube player in Moodle and enabling the "Use no cookie domain" option allows embedded Youtube videos to be played even when the user rejects all cookies.

Is it possible to make VideoEasy work with OneTrust cookie manager so that YT videos can be played from the no cookie domain?

**Comment by justinhunt** [comment]
I am sure we can figure that out. I think you are using the youtube lightbox player. Right?

**Comment by moodleacademy** [comment]
Yes that is correct. We're using the YT lightbox player.

**Comment by justinhunt** [comment]
I have a made a new template: "YouTube No Cookie (Lightbox)" Right click, download it from the link below and save it somewhere.
[youtubelightboxnocookie.txt](https://github.com/user-attachments/files/17201513/youtubelightboxnocookie.txt)

You should drag/drop that file over the green bundle box on an empty VideoEasy template settings page. Then save the page. (Chrome works bet for this)

Then wherever you have set VideoEasy to handle YouTube videos with the "YouTube (Lightbox)" player, change that to the "YouTube No Cookie (Lightbox)" player. Probably that is done at:
_Site Administration -> Plugins -> Filters -> VideoEasy -> General Settings_
(If anything goes wrong you can always switch back)

And thats it, videos will use the youtube-nocookie domain when loading. Hopefully that will work with OneTrust cookie manager. (I do not have it to test with myself)

Some notes. The last one is important:
* I will add the new template to VideoEasy, but there is no need to upgrade VideoEasy plugin. It will need changes for M4.5 they have not been done yet. Wait till then
* Though it looks the same we no longer use the same lightbox(featherlight) we use FancyBox, it should work at least as well. Possibly some behaviour is different. Let me know if there is something bad about that.
*  You have made some CSS and other tweaks. You might need to re-add those to the template. I looked at it and I think you just need to change the default size of the thumbnails from width: 240px height:160px to width: 100% height: 100% . Do that in the templates "defaults" text box.
* Finally and most crucially, the thumbnail itself does not load from the youtube-nocookie domain. The video does, but the thumbnail can not be loaded in the same way. Perhaps we can trust YouTube is not tracking cookies from the thumbnail, and more immediately I hope that OneTrust is ok with that. Please let me know how that goes

**Comment by moodleacademy** [comment]
Thanks for your suggestions.
Using the YT no cookie template resolved part of the issue. As for the thumbnails not loading when cookies are rejected, we used CSS to style the video player block instead of showing an ugly broken image icon.
